excerpt_separator: <!--more-->


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

# --- 网站信息设置 ---
# 下面填写你的博客标题
title: Punk
# 下面填写你的网络常用名
name: Punk
# 下面填写你的座右铭或者是个性签名
description: 自律
# 你博客的 url 地址，比如：https://showzeng.github.io 或者是自定义的域名
url: https://punk8.github.io
# 在页尾的版权时间信息，比如：2016-2018，默认是 2018 年
copyright_time: 2020
# 标签页的 logo 及博客的头像，如果你想引用网络图片资源，就取消下面的注解，并填写图片资源的 url 地址
# 或者，推荐的做法是将这两个图片资源下载到本地的 /assets/img/ 文件夹下，且图片名必须命名为 favicon 和 avatar
# favicon:
# avatar:
# --- 网站信息设置 ---


# --- 文章列表页 ---
# 文章列表是否显示摘要
show_excerpt: true
# --- 文章页 ---

# --- 社交链接 ---
# 取消下面的注解，并填写相应的你要开启的社交链接
#twitter: https://twitter.com/showzeng
github: https://github.com/punk8
# 邮件地址前面带上 mailto:
email: mailto:1041501690@qq.com
# RSS 订阅
rss: true
# --- 社交链接 ---



# --- 站点统计 ---
# 如果你想开启站点统计，取消下面一行注解，并填写相应统计运营商给的 id，可支持多个同时开启
#site_statistics: true
# cnzz (友盟统计)
#cnzz_id: 1274425891
# Baidu (百度统计)
baidu_id: 1b3b1dd10417c649478b6e267a85591f
# Google Analytics (谷歌统计)
# google_id:
# --- 站点统计 ---


# # --- 评论设置 ---
# # 开启评论，取消下面一行注解，并填写相应评论运营商提供的 id，目前仅支持来必力和 gitment
# comment: true
# # 来必力 uid
# # livere_uid:
# # gitment 用户主，即 GitHub 用户名
# gitment_owner: punk8
# # GitHub pages 仓库名，如：showzeng.github.io
# gitment_repo: punk8.github.io
# # gitment 提供的对应 id 和 secret
# gitment_client_id: 76bb22ffd69cb9a2dc11
# gitment_secret: 1bc48766be80fbcb2802679ab796d76ac4fafe44
# # --- 评论设置 ---

# theme: jekyll-theme-minimalism
remote_theme: showzeng/Minimalism

exclude:
  - new
